wings:

image: ghcr. io/pterodactyl/wingsv1.6.1restart alwaysnetworks:

- wings0ports:

"8080-8080

"2022-2022

- "443:443*

tty: trueenvironment:1Z: UTC

WINGS_UID: 988

WINGS_GID: 988

WINGS_USERNAME: pterodactyl

volumes:

- "Ivar/run/docker.sock/var/run/docker.sock

- "var/lib/docker/containers/:/var/lib/docker/containers/

"letc/pterodactyl/:/etclpterodactylr

- var/lib/pterodacty/:/var/lib/pterodacty

- "Ivar/log/pterodacty/var/log/pterodactyl

- "/mp/pterodacty/ /tmp/pterodactyr

- "/etc/ssl/certs:/etc/ssl/certsro"

# you may need /srv/daemon-data if you are upgradingfrom an old daemon

"/sv/daemon-data/:/srv/daemon-data/

# Required for ssl if you use let's encrypt. uncomment

to use.

# /etc/letsencrypt/:/etc/letsencrypt/"

networks:

wingso:

name: wings0

driver: bridge

ipam:

config:

- subnet: "172.21.0.0/16

driveropts:

com.docker.network.bridge.name: wings0
